version: '3.1'

services:
  blog_strapi_api:
    container_name: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres123456"
      POSTGRES_DB: blog-strapi
    ports:
      - "5432:5432"